### ISSUE TITLE
Issue with command elmfire_2023.0715

### ISSUE THREAD

**Issue by NogaGivoli** [lautenberger/elmfire#33] opened 2023-09-11 08:14 UTC
Hello (: 

When running any of the tutorials 1-4, we encountered the same error message: elmfire_2023.0715: command not found.

For example, in tutorial 1, the error message is as follows:

./01-run.sh: line 83: elmfire_2023.0715: command not found. 

This could point to an issue with the ELMFIRE_VER variable.

This bug did not occur just a week ago when using the elmfire_2023.06 version, which makes us think this issue may have something to do with a recent update. 

![error message tutorial 01](https://github.com/lautenberger/elmfire/assets/144664863/4f89cb9e-ec4a-4ce6-b50c-244ff25ff03b)

**Comment by lautenberger** [comment] 2023-09-11 14:10
Thanks, I've incremented the version number from 2023.0715 to 2023.0903 in commit https://github.com/lautenberger/elmfire/commit/23c8dc56a8f20ae2dd45f6b59844278df80ff24f. So clone the latest repo and you should be good to go!

**Comment by DesertLabRat** [comment] 2023-09-11 20:29
Tutorial 4 is still throwing an error for me.

```
./01-run.sh:    line 65:    313265 Killed            elmfire_$ELMFIRE_VER  ./inputs/elmfire.data
ERROR 4:    ./outputs/*.bil:    No such file or directory
```

Not sure what I'm looking at, hoping someone with more expertise can diagnose the root problem.

**Comment by lautenberger** [comment] 2023-09-14 17:16
That error message looks like ELMFIRE is running out of memory. Try on a PC or VM with more RAM.

**Comment by lautenberger** [comment] 2023-09-16 17:14
I've confirmed this tutorial runs correctly so closing this issue

**Closed by lautenberger** 2023-09-16 17:14 UTC
