### ISSUE TITLE
No Monte Carlo simulations

### ISSUE THREAD

**Issue by dwimjpurnomo** [lautenberger/elmfire#21] opened 2023-07-04 15:59 UTC
I tried to disable the perturbation by making the lower and upper bound to be equal. But when I try to do repetitions, the outputs are still different. How to make the outputs to be equal when we repeat simulations? 
Attached is the input decks and the outputs that I get.
https://drive.google.com/file/d/1n7ORrwuOdYdwQhtmF1Qq6HTUsa_Jfsuk/view?usp=sharing

**Comment by lautenberger** [comment] 2023-07-07 19:30
Even without perturbations on the inputs you will still see different outputs due to the stochastic nature of spotting. What happens if you disable spotting?

**Comment by lautenberger** [comment] 2023-07-08 22:52
@dwimjpurnomo I confirmed that with your input deck the outputs are the same for each ensemble member provided spotting is disabled and `WIND_FLUCTUATIONS = .FALSE.`. Enabling spotting or wind fluctuations is going to cause differences across ensemble members. Closing this issue.

**Closed by lautenberger** 2023-07-08 22:52 UTC
